version: '3.8'

services:
  rag-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      - FAISS_IMPL=GPU
      - LLM_CACHE_SIZE=2048
    volumes:
      - ../models:/app/models
